### ISSUE TITLE
Demo project not working anymore

### ISSUE THREAD

**Issue by quentingirard** [github/webauthn-json#74] opened 2023-02-03 13:39 UTC
Hello !

I've tried your demo and I get every time `Cannot interpret QR code`. My test was done on Chrome v109 and with Google Authenticator

Can it be related to the new WebAuthn L3 JSON serialization methods ?

- https://w3c.github.io/webauthn/#dom-publickeycredential-tojson
- https://w3c.github.io/webauthn/#sctn-parseCreationOptionsFromJSON
- https://w3c.github.io/webauthn/#sctn-parseRequestOptionsFromJSON

**Comment by lgarron** [comment] 2023-02-03 23:57
> My test was done on Chrome v109 and with Google Authenticator

Could you elaborate what this means? I could possible debug this if I had a reproducible case.

**Comment by quentingirard** [comment] 2023-02-06 07:49
Sure !

- https://github.github.com/webauthn-json/demo/
- Click on **Register**
- In my case **Chrome** asked for a USB Key, say no
- Choose **Other devise**
- Scan QR Code with **Google Authenticator**
- On my **Google Authenticator** a pop-up comes in with **Cannot interpret QR Code**

I've tested with **Edge** and **Chrome** in private mode too with the same result. I Also tested with **Synology Secure Signin** as an alternative for **Google Authenticator**

**Comment by lgarron** [comment] 2023-02-10 19:05
> * Scan QR Code with **Google Authenticator**

Google Authenticator is used for [TOTP codes](https://en.wikipedia.org/wiki/Time-based_one-time_password), which is a completely incompatible format with WebAuthn registration. (Same with Synology Secure Signin it seems.)

I would expect that this never worked. Are you certain that it used to work for you?

If you're trying to register a WebAuthn from another device onto an iPhone, you should use the main camera. I'm not sure how Android devices handle it. I know it's a bit confusing, but this is an ecosystem challenge outside the scope of the library.

**Comment by lgarron** [comment] 2023-02-12 02:49
Closing for now since I don't think there's anything actionable for the project.

**Closed by lgarron** 2023-02-12 02:49 UTC

**Comment by quentingirard** [comment] 2023-02-13 08:03
It worked for me until approx 2-3 weeks. I successfully implemented in my project.
